version: '3'
services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
  admin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=root"
      - "PGADMIN_DEFAULT_PASSWORD=root"
